#!/bin/sh

echo "*********************************"
echo "** lemmy-iai install script v1 **"
echo "*********************************"

printf "finding out the latest version number..."
LAST=$(curl -s https://raw.github.com/laconbass/lemmy-iai/master/lemmy/version)
printf ' done.\n'

echo ""
echo "This script will install lemmy-iai $LAST on the CWD."
echo "The current working directory (CWD) is:"
echo "    $(pwd)"

KEYWORD="continue"
while [ "$answer" != "$KEYWORD" ]; do
  if [ "$answer" = "exit" ]; then
    exit 1
  fi
  echo "Enter '$KEYWORD' to proceed with installation, 'exit' to abort."
  read answer
done

INSTALL_TMP_DIR=lemmy-install-tmp
LEMMY_REPO=https://github.com/laconbass/lemmy-iai.git
LEMMY_DIRECTORY=lemmy

printf '\n%s\n' "dowloading lemmy-iai..."
printf '\t%s\n' "from $LEMMY_REPO"
printf '\t%s\n\n' "to $INSTALL_TMP_DIR"
git clone $LEMMY_REPO $INSTALL_TMP_DIR

printf '\n%s\n' "moving lemmy files to the CWD"
rm -rf $LEMMY_DIRECTORY
mv $INSTALL_TMP_DIR/$LEMMY_DIRECTORY .

printf '\n%s\n' "set include on Makefile"
INCLUDE_FILE=$LEMMY_DIRECTORY/includes
cat Makefile | grep -v "include $INCLUDE_FILE" | cat -s > Makefile
printf '\n\ninclude %s # include lemmy\n' "$INCLUDE_FILE" >> Makefile

printf '\n%s\n' "removing temporary installation directory..."
rm -rf $INSTALL_TMP_DIR

printf "\ndone.\n"
